packages:
  - 'extensions/*'
  - 'tooling'

allowBuilds:
  esbuild: true

catalog:
  '@girs/gjs': 4.0.0-rc.15
  '@girs/gnome-shell': '^50.0.0'
  '@girs/gnome-shell-46': 'npm:@girs/gnome-shell@46'
  '@girs/gnome-shell-47': 'npm:@girs/gnome-shell@47'
  '@girs/gnome-shell-48': 'npm:@girs/gnome-shell@48'
  '@girs/gnome-shell-49': 'npm:@girs/gnome-shell@49'
  '@girs/gnome-shell-50': 'npm:@girs/gnome-shell@50'
  '@types/node': '^25.6.2'
  '@vitest/ui': '^4.1.5'
  esbuild: '^0.28.0'
  oxfmt: '^0.48.0'
  oxlint: '^1.63.0'
  typescript: '7.0.1-rc'
  vite: '^8.0.11'
  vitest: '^4.1.5'
  '@helpers4/array': '^3.0.0'
  '@helpers4/color': '^3.0.0'
  '@helpers4/object': '^3.0.0'
  '@helpers4/promise': '^3.0.0'
  tsx: '^4.22.4'

minimumReleaseAgeExclude:
  - mozlz4@0.2.2
  - sqlite-reader@0.2.1
  - '@helpers4/array@3.0.0'
  - '@helpers4/color@3.0.0'
  - '@helpers4/object@3.0.0'
  - '@helpers4/promise@3.0.0'
