packages:
  - 'extensions/*'
  - 'tooling'

allowBuilds:
  esbuild: true

catalog:
  '@girs/gjs': 4.1.0
  '@girs/gnome-shell': '^50.0.4'
  '@girs/gnome-shell-46': 'npm:@girs/gnome-shell@^46.0.2'
  '@girs/gnome-shell-47': 'npm:@girs/gnome-shell@^47.0.2'
  '@girs/gnome-shell-48': 'npm:@girs/gnome-shell@^48.0.4'
  '@girs/gnome-shell-49': 'npm:@girs/gnome-shell@^49.1.0'
  '@girs/gnome-shell-50': 'npm:@girs/gnome-shell@^50.0.4'
  '@types/node': '^26.2.0'
  '@vitest/ui': '^4.1.10'
  esbuild: '^0.28.2'
  oxfmt: '^0.62.0'
  oxlint: '^1.77.0'
  typescript: '7.0.2'
  vite: '^8.2.1'
  vitest: '^4.1.10'
  '@helpers4/array': '^3.0.7'
  '@helpers4/color': '^3.0.7'
  '@helpers4/object': '^3.0.7'
  '@helpers4/promise': '^3.0.7'
  tsx: '^4.23.11'

minimumReleaseAgeExclude:
  - '@helpers4/array@3.0.6'
  - '@helpers4/color@3.0.6'
  - '@helpers4/object@3.0.6'
  - '@helpers4/promise@3.0.6'
  - mozlz4@0.2.4
  - sqlite-reader@0.3.0
